[apps.connector_76869538009648d5b282a4bb21c3d157]
default_tools_approval_mode = "approve"
default_tools_enabled = true
enabled = true

command = "npx"

[plugins."cloudflare@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true
