#:schema node_modules/wrangler/config-schema.json
name = "evergreen-io"
main = "dist/_worker.js"
compatibility_date = "2025-07-06"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build && bun build src/worker.ts --outfile=dist/_worker.js --target=browser"

[assets]
directory = "dist"
binding = "ASSETS"

[env.production]
name = "evergreen-io"

[env.staging]
name = "evergreen-io-staging"

[env.development]
name = "evergreen-io-dev"

# Custom domains - automatically creates DNS records and manages certificates
[[routes]]
pattern = "evergreenlabs.io"
custom_domain = true

[[routes]]
pattern = "www.evergreenlabs.io"
custom_domain = true

# KV namespaces (if needed for caching or data storage)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# R2 buckets (if needed for file storage)
# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "evergreen-files"

# Analytics and observability
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

# Limits and performance
